#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#load shared and private functions
for function in ~/.dotfiles/zsh/includes/*; do
  source $function
done

if [[ -d ~/.zsh_includes ]]; then
  for function in ~/.zsh_includes/*; do
    source $function
  done
fi

#load shared and 'private' aliases
[[ -f ~/.dotfiles/zsh/aliases ]] && source ~/.dotfiles/zsh/aliases
[[ -f ~/.aliases ]] && source ~/.aliases

# added by devctl command
[ -f /opt/devctl/devctl.sh ] && source /opt/devctl/devctl.sh
