#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

[[ -s ~/.zplug/init.zsh ]] && source ~/.zplug/init.zsh

#load shared and private functions
for function in ~/.dotfiles/zsh/includes/*; do
  source $function
done

if [[ -d ~/.zsh_includes ]]; then
  for function in ~/.zsh_includes/*; do
    source $function
  done
fi

#load shared and 'private' aliases
[[ -f ~/.dotfiles/zsh/aliases ]] && source ~/.dotfiles/zsh/aliases
[[ -f ~/.aliases ]] && source ~/.aliases

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

zplug load 

[ -f /Users/benjamincaldwell/.devctl/devctl.sh ] && \. /Users/benjamincaldwell/.devctl/devctl.sh # This loads devctl shell super powers
